### ISSUE TITLE
remove node list from the dashboard

### ISSUE THREAD

**Issue by tomerweller** [stellar/dashboard#107]
- The node list is incomplete 
- It requires manual updates
- It's misleading as people might think that the availability metric relates to validation while in fact it's just overlay (https://github.com/stellar/dashboard/issues/49)
- removing it allows the dashboard to be focused on one thing: ledger activity.    
- stellarbeat.io does a better job. we can link to that

**Comment by kissingyou1** [comment]
cryptomover.net:11625
