### ISSUE TITLE
cluster validators by entity

### ISSUE THREAD

**Issue by tomerweller** [stellar/dashboard#14]
As more validator nodes join, the list becomes cluttered.
I propose clustering the nodes by entities - like "ibm" and "sdf"
Then instead of showing a list of nodes, we will show a list of entities - each one summarizing all of the entity's nodes.

**Comment by chriserice** [comment]
+1 to the Group by (and _sorted by_) entity name idea. The 5/21 update to include host names column will differentiate nodes within the group.

**Comment by bartekn** [comment]
We started displaying nodes in a random order (you can also order alphabetically but random is default) and pagination. I think this solves the main issue here which was long list of nodes.
