### ISSUE TITLE
Local time in Scheduled Maintenance banner incorrect

### ISSUE THREAD

**Issue by bartekn** [stellar/dashboard#142]
### What version are you using?

Latest deployed as of this issue creation time.

### What did you do?

The local time in the Scheduled Maintenance banner is incorrect for me:
> Scheduled Maintenance: Public Network Protocol 13 Upgrade Vote on Thursday, June 4th 2020, at **4:00pm UTC** (**4:00pm** local time)

I'm in Poland and we're in UTC+2 timezone on June 4th: https://www.worldtimebuddy.com/?qm=1&lid=756135,100&h=756135&date=2020-6-4&sln=18-19.

**Comment by jeesunikim** [comment]
Fixed via [PR 145](https://github.com/stellar/dashboard/pull/145)
