### ISSUE TITLE
how to do transactions+op per second

### ISSUE THREAD

**Issue by gomadosnitro** [stellar/dashboard#18]
Im trying to add in dashboard a javascript to add transactions+op per second, its a good indicator about network .

for example 1 trasaction in 200 ledgers with  average of  5 seconds per transacion in 200 ledgers. Will be average transations per second 1/(200*5)sec so the final data i want to see in dashboard will be like
 0.001 tx/sec.

or divided per 60 seconds. Num transacions in one minute /60 .

i think will be a good indicator.

**Comment by gomadosnitro** [comment]
ok i only have to sum total number of last 200 transactions and divided averageLedgerLength*200 
in networkstatus.js 
but dont know how to sum last 200, every time.

**Comment by bartekn** [comment]
We already have chart for txs and ops per day which I think is a better indicator that txs/sec in the last 200 ledgers.
