### ISSUE TITLE
Feature Request: Improvements to the lumens API

### ISSUE THREAD

**Issue by satyamz** [stellar/dashboard#181]
### What problem does your feature solve?
When we use `/api/v2/lumens` API it returns values in the float format. It would be very useful to have values of `/api/v2/lumens` API to be reported as a whole numbers, to achieve that we can multiply current number with `10^7`. We can consider adding a new filter to the API to return values in the different format.

Currently, programming languages such as javascript (old version), python etc. truncate the fraction part of the number and that makes it very difficult to get exact `totalSupply` number. It'd be great to have `totalSupply` and other fields provided as whole numbers.

### What would you like to see?
In addition to the whole number support, it'd also be useful to have `totalSupply` sanity check inbuilt in the API. API should return following two numbers:
1. `lumensSupply` = `totalSupply` - `feePool`
2.  `circulatingLumensSupply`= `upgradeReserve` + `circulatingSupply` + `sdfMandate`

Above two numbers should be same. This will ensure that `totalSupply` will always be equal to sum of four categories `upgradeReserve`, `circulatingSupply`, `sdfMandate` and `feePool`.

(Nomenclature for the above two numbers can be different too.)

### What alternatives are there?
None!

**Comment by acharb** [comment]
@satyamz with this merged for the Blazemeter Total Lumens test the endpoints to compare are:
`/api/v3/lumens/total-supply-check` and
`/api/v3/lumens/total-supply`

and can be compared with the strings directly so no parsing is needed
