### ISSUE TITLE
TXS & OPS IN THE LAST 30 DAYS: LIVE NETWORK

### ISSUE THREAD

**Issue by swetakedia** [stellar/dashboard#19]
I am getting error when the section - TXS & OPS IN THE LAST 30 DAYS: LIVE NETWORK is getting loaded. On checking details getting following : 
![image](https://user-images.githubusercontent.com/30261014/34293524-0b33baf6-e72b-11e7-9c0a-7bb381800dae.png)

in multiple places in code the url is just pointing to axios.get('/ledger/public')  or axios.get ('/api/nodes') or axios.get('/api/lumens') But it is not found. How do i resolve this. Which component is missing. I have just followed the steps given in build instructions.

**Comment by swetakedia** [comment]
I get the issue - streaming is not working 
```
var horizon = new stellarSdk.Server('https://horizon.stellar.org');
horizon.ledgers().cursor(pagingToken).stream({
onmessage: function(ledger) {
var date = moment(ledger.closed_at).format("YYYY-MM-DD");
var key = "ledger_public"+date;

  var multi = redisClient.multi();
  multi.hincrby(key, "transaction_count", ledger.transaction_count);
  multi.hincrby(key, "operation_count", ledger.operation_count);
  // Expire the key after 32 days
  multi.expire(key, 60*60*24*32);
  multi.set("paging_token", ledger.paging_token);
  multi.exec(function (err, res) {
    if (err) {
      console.error(err);
      return;
    }
    console.log("Added Ledger:"+ledger.sequence+" "+ledger.closed_at+" "+res);
  });
}
});
});

```
Above code is not working. It is getting terminated. Anyone has any idea on how streaming will work?

**Comment by bartekn** [comment]
Please follow the instructions in https://github.com/stellar/dashboard#building.

If you run the server like `DEV=true node app.js` and `gulp` (in another terminal). It will start a proxy at `localhost:5000` to `localhost:3000` (where frontend is served). This will allow you to access all the API endpoints.
