### ISSUE TITLE
Zimbabwean Currency Inclusion

### ISSUE THREAD

**Issue by Plot62** [stellar/dashboard#239]
### What problem does your feature solve?

Removal of the stigma that exists around the country's economy.

### What would you like to see?

Full cross-border payments, including the Trans-Border Reserve System that Zimbabwe, South Africa and Mozambique (along with the other Southern African Development Conference regional and global partners) have been working on for decades.

### What alternatives are there?

Currently, I believe a still semi-opaque banking system out of the Isle of Man.

**Comment by acharb** [comment]
closed because doesn't seem relevant for this GH project
