### ISSUE TITLE
Update project config to serve frontend from express

### ISSUE THREAD

**Issue by quietbits** [stellar/dashboard#242]
We need to serve frontend and backend code from the express. The current configuration doesn't work for the backend because we're using CRA to serve the frontend.

**Comment by MassiGy** [comment]
Hey there, 
I'am a backend developer, and I'am very comfortable using Express for my server code. I would love to contribute on this.

Can you refer me to the `server.js` file and the views so as we can create API endpoints and render the views as responses for those.

Massiles.
