### ISSUE TITLE
By the numbers

### ISSUE THREAD

**Issue by quietbits** [stellar/dashboard#255]
Build the "By the numbers" section following the design.
- The container component `ByTheNumbers` is already [created](https://github.com/stellar/dashboard/tree/dashboard-v2/frontend/src/components/ByTheNumbers).
- Use [Stellar Design System](https://design-system.stellar.org/) (SDS) components as much as possible.
- Use only colors from the SDS to make sure light and dark modes "just work". We don't have color palette on the SDS website yet, so they can be found [here](https://github.com/stellar/stellar-design-system/blob/main/%40stellar/design-system/src/global.scss) or viewed in browser dev tools.
- Icons should also be used from the SDS (`<Icon />` component). It's OK if they differ slightly.
- Will need a backend endpoint to get the data.
- Only on mainnet (no testnet).

![image](https://user-images.githubusercontent.com/7346473/165760570-7b45f1a5-2519-46b3-9fc9-877545795003.png)

![image](https://user-images.githubusercontent.com/7346473/165766460-6fff9384-bd70-45b4-bf36-ddb0a71186e4.png)

Some notes

![image](https://user-images.githubusercontent.com/7346473/165761418-7aad9f6e-69af-46e3-971e-5a0ee47665e2.png)

**Comment by italomlp** [comment]
@quietbits I noticed a comment/todo on the `By the numbers` related component, saying to update the link. Could you give me some context on this? I mean, which link should I put there? Should it be dynamically generated in some way? Thanks in advance.

**Comment by quietbits** [comment]
@italomlp, we will need to check with the project manager on this. I don't think we decided which link we want to put there, but it should be something for the DEX data we display there. I'm not sure if we're creating a backend endpoint for this or using something already available. In short, the idea is to use the data source link for "More stats".

**Comment by italomlp** [comment]
Sure. We are doing an endpoint to get these data from Hubble, and I just started the integration. I'll ping the team about it. Thank you!
