### ISSUE TITLE
Fee Module 

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#273]
Build a "Fees" container component with the following elements:

1. Average Transaction Fee: 0.0002 XLM
   - [Reference example](https://messari.io/asset/stellar/chart/txn-fee-avg)
2. Graph of Average Transaction Fee over time (24hr, 30d)
   - May need to be derived from Hubble data and stored in time series
4. Base operation fee: 0.00001 XLM 
   - Src: static variable from code
5. Base reserve: 0.5 XLM
   - Src: static variable from code  
6. Fee Stats (Last 5 Ledgers) 
   - Metric | Value

Considerations:

- The "Fees" container component will need to be created
- Use [Stellar Design System](https://design-system.stellar.org/) (SDS) components as much as possible.
- Icons should also be used from the SDS (<Icon /> component). It's OK if they differ slightly.
- Backend data will vary depending on the data element
- Only on Mainnet (no Testnet).

**Comment by raphaelmartins1993** [comment]
[jcx120](https://github.com/jcx120)
**Average Transaction Fee: 0.0002 XLM**

> Could you send us more information about the calc to this average?

**Graph of Average Transaction Fee over time (24hr, 30d)**

- May need to be derived from Hubble data and stored in time series

> Is it possible to bring us more context about this data source from Hubble? Which tables, etc.

3. Base operation fee: 0.00001 XLM
4. Base reserve: 0.5 XLM

> These two information are fixed?

**Comment by italomlp** [comment]
Here are some screenshots of the possible final chart for this Fee module. Feedback is much appreciated, maybe for changing some colors, spacings, etc. LMK your thoughts @jcx120

<details>
<summary>Click to see screenshots:</summary>

PS: I'm using fake values, don't take them into account.

<img width="785" alt="Screen Shot 2022-06-09 at 15 04 21" src="https://user-images.githubusercontent.com/17295921/172918304-edc7322a-95ef-420c-a290-2a4363af5a6d.png">
<img width="781" alt="Screen Shot 2022-06-09 at 15 04 30" src="https://user-images.githubusercontent.com/17295921/172918315-3da46466-8004-4a93-b9ee-74f31cfc18d4.png">
<img width="766" alt="Screen Shot 2022-06-09 at 15 04 40" src="https://user-images.githubusercontent.com/17295921/172918340-24a169bc-b4ed-4a46-9c31-2ac28b40d417.png">
<img width="776" alt="Screen Shot 2022-06-09 at 15 04 54" src="https://user-images.githubusercontent.com/17295921/172918355-eea2f720-549f-45b9-8c33-5d95ab391f26.png">

</details>

**Comment by jcx120** [comment]
Design wise, they look good (maybe the last one is preferred).

**Comment by raphaelmartins1993** [comment]
Hello @jcx120, we have a question about Fee Stats (last 5 ledgers). 
We would like to know if this information should be **real time**.

Analyzing the dashboard v1, we believe that this data is in real time. Therefore, we will be able to use the data we have in the frontend related to ledgers.

The other option would be to collect this data directly through the SDK with Horizon.

Can you confirm this information for us?
Thank you so much!

**Comment by jcx120** [comment]
Yes, this can be in "near real time" given its last 5 ledgers. The fee stats api call should give you everything you need:
https://horizon.stellar.org/fee_stats

**Comment by lccoronel** [comment]
Hi @jcx120, we did the "Fee Stats (last 5 ledgers)" table, following the dashboard v1 and applying the Stellar`s Design system, it was like this: 

<img width="1792" alt="Screen Shot 2022-06-21 at 09 54 35" src="https://user-images.githubusercontent.com/54275445/174812025-f71bb9fb-a3a4-47fa-9e96-742a6c607769.png">

we still need apply and adjust somethings, but what do you think?

**Comment by jcx120** [comment]
Looks good - one minor thing is to add a label to the units (stroops). Like this:

"Fee Stats (Last 5 ledgers), Fee unit in [stroops]([url](https://developers.stellar.org/docs/glossary/fees/)))"

once all the data is in these modules, we'll have UX to do a review and adjust the design if needed.

**Comment by raphaelmartins1993** [comment]
Hi @jcx120!!

During the development of this task, we came across a few questions.

- The query you gave us would give the average of transaction fees for the entire month, this made us unsure as to whether this data should be displayed somewhere directly or in a graph. If it's a graph, we would need a different query to show data in an interval (such as 30 24hrs interval data points for 30 days graph).

- Is the data from this query already the values we want to display? Or do we need to multiply them for the price of a specific asset such as XLM?

Thank you!

**Comment by jcx120** [comment]
@raphaelmartins1993 

1. You'll need to adjust the query parameters to get the other intervals. A graph over the standard intervals (1HR, 24Hr, 30D) would be nice to have. 
2. Fees are usually in stroops (and should be labeled as such) - but play around with it and see. See comment: https://github.com/stellar/dashboard/issues/273#issuecomment-1162005865

**Comment by lccoronel** [comment]
#302
