### ISSUE TITLE
Transactions Module

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#274]
Build a "Transactions" container component with the following elements:

1. Transactions Per Second (TPS): 120
   - Current TPS
   - [Reference for src calculation method](https://www.realtps.net/) 
2. Historical TPS - last 30 days (Nice to have)
   - Graph chart of average daily TPS over past 30 days, MainNet only
3. Recent Operations 
   - See legacy Dashboard
   - Last 10
   - Fields: Source Operation | Details | Time ago

Considerations:
- The "Transaction" container component will need to be created
- Use [Stellar Design System](https://design-system.stellar.org/) (SDS) components as much as possible.
- Icons should also be used from the SDS ( component). It's OK if they differ slightly.
- Backend data will vary depending on the data element
- On Mainnet and TestNet

**Comment by raphaelmartins1993** [comment]
@jcx120 
Where we can get these operations? Horizon or Hubble?
If Hubble, which tables?

**Comment by raphaelmartins1993** [comment]
hello @jcx120, in the historical TPS of the transactions module we should always bring the last 30 days fixed, or should we also have the possibility of filters such as 1 hour, 1 day, 30 days?
thanks!

**Comment by jcx120** [comment]
@raphaelmartins1993 If this is easy to do, then let's have the 1hr, 1day, 30 day filter to keep it consistent with other metrics. Otherwise, let's keep it fixed at 30 days.

**Comment by lccoronel** [comment]
Hi @jcx120 and @quietbits, we just did the transactions component with "Transactions Per Second" and "Historical TPS", what do you think of the layout?

<img width="839" alt="Screen Shot 2022-06-28 at 15 58 21" src="https://user-images.githubusercontent.com/54275445/176266134-b77fb127-d070-486d-97cc-9bf91f049062.png">

**Comment by jcx120** [comment]
I think it looks fine. We can have Charles review it once a staging instance is available so it can be seen in context.

**Comment by lccoronel** [comment]
ok, we have a preview here: https://dashboard-pr293.prototypes.kube001.services.stellar-ops.com/?network=mainnet

**Comment by lccoronel** [comment]
@jcx120 and @quietbits, another thing, I noticed that the "RECENT OPERATIONS: LIVE NETWORK" table on dashboard v1 some data is treated that is not returning in the [horizon API ](https://horizon.stellar.org/operations?order=desc&limit=200) like: 

* operation name
* operation shares_received
* shares

like others fields.

![code](https://user-images.githubusercontent.com/54275445/176921431-7f89b68a-273a-4a8e-a997-869d7ffcb16b.png)

Are these data retrieved at some point in an operation or can we disregard them?

**Comment by jcx120** [comment]
> 

Cool! I'm assuming the [Fees module](https://github.com/stellar/dashboard/issues/273) and [Ledger module](https://github.com/stellar/dashboard/issues/275) are coming soon correct?

**Comment by lccoronel** [comment]
yes, we are intending to finish this in the next days

**Comment by cbshin-stellar** [comment]
UX and visuals look great! no feedback to add, it's pretty 1:1 with the design so I'm happy with how the staging looks currently

**Comment by cbshin-stellar** [comment]
For Recent Operations, we can limit the number of items displayed to 10 rows.

**Comment by lccoronel** [comment]
Hi @jcx120, we still need to check this account?

![code](https://user-images.githubusercontent.com/54275445/177556220-4bd40f1b-bc48-4807-9db8-4ce488098ab8.png)

I was chatting with @quietbits and I had this doubt?

**Comment by acharb** [comment]
@lccoronel let's remove it, doesn't look critical to me

**Comment by jcx120** [comment]
@lccoronel For the "Transactions Per Second" Module, lets:

1. Move the "Current TPS" box to be above the graph
2. Change the "Transactions" label for the graph to be "Average Daily Transactions"

This is so the most important info is available at the top. thanks

**Comment by jcx120** [comment]
@lccoronel Looking good and thanks for the updates. One minor text change:
For the "Ledger Operations" module, please update the "Operations" text (next to the dot) to be "Total monthly operations"

**Comment by lccoronel** [comment]
#302
