### ISSUE TITLE
Ledger module

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#275]
Build a "Ledger" container component with the following elements:

1. Operations Capacity: Monthly graph of Operations (million) (y axis) vs Time (x axis) with a static max red line indicating capacity limit (Operations (million) per month) 
   - Data is in Hubble
2. % Operations Capacity Utilized current month
   - This is a current month view of utilization 

Considerations:
- The "Ledger" container component will need to be created
- Use [Stellar Design System](https://design-system.stellar.org/) (SDS) components as much as possible.
- Icons should also be used from the SDS ( component). It's OK if they differ slightly.
- Backend data be from Hubble
- On Mainnet (and not TestNet)

**Comment by raphaelmartins1993** [comment]
@jcx120 
Could you bring us more information about [this link](https://stellarfoundation.slack.com/archives/C02B04RMK/p1651588338318189?thread_ts=1634587865.341700&cid=C02B04RMK)? We don’t have permission to access it.

We want to know the maximum capacity to display the red line in the chart.

- This number is static or dynamic?

If you can explain more about what information we need to use in Hubble.

**Comment by jcx120** [comment]
For this module, the query is in Hubble. For details we can reach out to @bartekn 
The link is just the original slack thread that has the context (but not the query)

**Comment by raphaelmartins1993** [comment]
Hi @jcx120. We have a question about the **trendline** that is displayed in the graph. Since we haven't seen any specification about it, we would like to know if it should be shown or not?
If it should be displayed, can you tell us if it is calculated or static?
Thank you very much!

**Comment by jcx120** [comment]
That trendline is not MVP scope and can be left out (I think its a r^2 trendline generated in excel). 

We do want that Max red line which is a constant for the maximum # of operations per month based on theoretical capacity of 5000 operations per second. @bartekn can you share that number? thanks

**Comment by jcx120** [comment]
I like option 3 but once its prototyped we can also have our UX designer provide input. thanks

**Comment by italomlp** [comment]
Oh, sorry, maybe I was not so clear. They are the same component, in light and dark mode variants. Also, the one that has a tooltip (image 2) is just the light mode variant with the mouse hovering over the chart. Does that make sense?

**Comment by bartekn** [comment]
[Here's](https://github.com/stellar/dashboard/issues/275#issuecomment-1147795658) how you can calculate it.

**Comment by lccoronel** [comment]
@acharb and @jcx120, in the graph of the ledgers module, do you need to have a period variation?

<img width="292" alt="Screen Shot 2022-07-08 at 10 40 50" src="https://user-images.githubusercontent.com/54275445/178003530-24e7b6ea-8056-4236-8348-dd8db2f6973b.png">

Or will we have a fixed period?

**Comment by acharb** [comment]
@lccoronel I think we want just the month timeline, based off of what @jcx120 said here
> 1. Operations Capacity: Monthly graph of Operations

**Comment by lccoronel** [comment]
Is this red line right?

<img width="836" alt="Screen Shot 2022-07-11 at 14 54 41" src="https://user-images.githubusercontent.com/54275445/178327807-773e2362-ac94-4c72-93e0-455d3aafc6af.png">

**Comment by jcx120** [comment]
@lccoronel I believe the units are missing 3 extra digits. So 518k should be 518 Million. 
We can label the value as "(Millions)" and put a decimal after the first 3 digits. Ie: 518.400 (Millions). See the sample in the original doc.

**Comment by lccoronel** [comment]
> @lccoronel I believe the units are missing 3 extra digits. So 518k should be 518 Million. We can label the value as "(Millions)" and put a decimal after the first 3 digits. Ie: 518.400 (Millions). See the sample in the original doc.

Actually we wrote 518 Million 😅

![code](https://user-images.githubusercontent.com/54275445/178335511-b3f21434-8dd4-42d9-9511-376401970065.png)

**Comment by jcx120** [comment]
@lccoronel Indeed you did it correctly! I need new glasses. 😅
