### ISSUE TITLE
Issue with error overlay on frontend in development mode

### ISSUE THREAD

**Issue by italomlp** [stellar/dashboard#279]
Hey guys. When I was working in some tasks, I noticed an invisible overlay/iframe that stays over everything. First, I was thinking it was related to my environment, but after some research, I found [this issue](https://github.com/facebook/create-react-app/issues/11773) on the `create-react-app` repository. It's related to our current version of CRA and one of its dependencies (`react-error-overlay`).

We have two options here:
1. Make a workaround using `yarn resolutions` strategy, like said in [this comment](https://github.com/facebook/create-react-app/issues/11773#issuecomment-996926736); or
2. Upgrade CRA to latest version (v5+). For this point, I started doing the upgrade, but the StellarSDK uses the https://github.com/EventSource/eventsource library, and it needs some polyfills to work properly.

I prefer the second option, but wanted to check your thoughts about it. @quietbits @acharb @Selhar

**Comment by quietbits** [comment]
Hi @italomlp ! We're actually in the process of replacing CRA with a custom webpack config for our frontend projects. Upgrading to CRA v5 needs those polyfills which we can't add manually. We should have a PR for this later this week. I'll tag you on it.
