### ISSUE TITLE
Dashboard v2 - Grouping and Ordering 

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#301]
Given the number of modules now on the dashboard, let’s group modules logically by area. 

Here’s the order (note that some have been nested):

1. Protocol Version
2. Last Ledger
3. Ledger Info
4. Last 10 Ledger Info 
5. Ledger Operations
   - [Total Monthly Operations](https://github.com/stellar/dashboard/issues/274#issuecomment-1197064099) 
   - Recent Operations: Live Network (nest this module)
8. Transactions Per Second
9. Transaction Fee Info
10. By the Numbers
   - Total XLM Issued (add / nest module at bottom)
   - Network Nodes (add / Nest module)
9. Incidents

**Comment by jcx120** [comment]
CC @cbshin-stellar

**Comment by lccoronel** [comment]
https://github.com/stellar/dashboard/pull/302
