### ISSUE TITLE
Dashboard v2 - Backend data not updating some modules (BUG)

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#305]
Build here: https://dashboard-pr304.prototypes.kube001.services.stellar-ops.com/?network=mainnet

A few modules seem to not be updating data (not sure if its a backend issue):

1. Total Monthly Operations
Not updating for July (month has closed) and should have a new bar for July:
<img width="903" alt="Screen Shot 2022-08-02 at 1 14 10 PM" src="https://user-images.githubusercontent.com/91218921/182464928-c9ad053f-0683-47c3-9ac3-ff645afeb217.png">
This is from a different dashboard for reference: <img width="1086" alt="Screenshot 2022-08-02 at 10 54 57" src="https://user-images.githubusercontent.com/91218921/182464550-500bef93-f6cf-49d6-90c4-40005db7830c.png">
2. Average Transaction Fee by Day (in stroops)
-- Not updating for recent days past 7/18 (for both 24H and 30D)
<img width="770" alt="Screen Shot 2022-08-02 at 1 15 13 PM" src="https://user-images.githubusercontent.com/91218921/182465118-08956571-10d8-43a5-a73d-eea2df4c017a.png">

**Comment by Selhar** [comment]
The data on the preview environment is static for the most part. Basically, some data goes through bigquery that requires authentication which the preview environment doesn't have, so we ask @acharb to create a cache for us in that environment. But this means that the preview environment is unable to update itself. In production this should be fixed.

**Comment by jcx120** [comment]
Thanks @Selhar . I'll close this issue for now.

**Comment by jcx120** [comment]
Expected behavior in Preview env's. Should be updating w live data in Prod.
