### ISSUE TITLE
Dashboard v2 - Production Deployment

### ISSUE THREAD

**Issue by jcx120** [stellar/dashboard#307]
All tasks needed for deploying this to production:

1. Create new domain: metrics.stellar.org (Ops)
(This is so we can keep the [legacy dashboard](https://dashboard.stellar.org/) up and deprecate later)
2. Network configuration (DNS, mappings etc), (Ops)
3. Ensure backend Hubble data (buckets, caches) are ready to go, deployed
4. Update Jenkins and other tooling to deploy to new `metrics` domain from GitHub `dashboard` repo.
5. Ensure front end artifacts are deployed

Staging for reference: 
https://dashboard-pr304.prototypes.kube001.services.stellar-ops.com/?network=mainnet

**Comment by jcx120** [comment]
CC: @acharb @quietbits

**Comment by acharb** [comment]
As part of #3 I have to set up the cron jobs for clearing stale cached DEX data on the backend ([ticket](https://github.com/stellar/dashboard/issues/277)). (CKL can't do since it'll be in the private Kube repo)

I can set up this week

**Comment by satyamz** [comment]
Hi @jcx120,
Hi Jesse, I created a CNAME record for [metrics.stellar.org](http://metrics.stellar.org/) which is pointing to prod ingress. You just have to specify this address when creating ingress for the new dashboard service.

**Comment by acharb** [comment]
this has been deployed so closing
