### ISSUE TITLE
toggle test vs public network

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/dashboard#51]
I think we should follow what we did for laboratory (with a toggle at the top) and only display (and download of course) testnet or pubnet instead of a giant combined page (default pubnet):
* this would make the page mobile friendly (right now it's so resource hungry that it doesn't display the right data over slow networks)
* it would mitigate to a certain extent the flickering caused by last transactions and validator health status (right now, because testnet is below pubnet, it jumps quite a bit)

**Comment by acharb** [comment]
this has been added to dashboard-v2, and can be viewed at https://metrics.stellar.org/?network=mainnet
