### ISSUE TITLE
use horizon time

### ISSUE THREAD

**Issue by tomerweller** [stellar/dashboard#88]
The delta between current time and last ledger close time uses the browser's clock. That's not always accurate. We should use a more accurate timestamp, perhaps from horizon.

**Comment by tomerweller** [comment]
Quick fix: assuming the offset is fairly fixed, we can just grab time from horizon's headers when making our first request, calculate the offset, and apply it when we measure the delta.

**Comment by morleyzhi** [comment]
This functionality already exists in stellar-sdk:

https://stellar.github.io/js-stellar-sdk/Server.html#fetchTimebounds

**Comment by tomerweller** [comment]
@morleyzhi it doesn't look like this `stellar-sdk` feature works from the browser. It relies on horizon's  response containing a [`date` header](https://github.com/stellar/js-stellar-sdk/blob/5607d31bd528bb46968f3d7e6ef79a7ea7c6f0f0/src/horizon_axios_client.ts#L40). However, this is not a CORS approved header and AFAIK horizon doesn't set [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

**Comment by tomerweller** [comment]
[Horizon 1.0.1](https://github.com/stellar/go/releases/tag/horizon-v1.0.1) now exposes date headers to CORS clients so we can use these
