### ISSUE TITLE
Show what ledger number it is when you mouse over the graphs

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/dashboard#90]

**Comment by dangdennis** [comment]
The current library implementation requires a fix to allow onMouseEnter and onMouseLeave props to passed down properly, which it currently doesn't. 

Made issue #96 to recommend a progressive move to a new data viz library. Unsure if this is an active Stellar project or will be rebuilt eventually though.

**Comment by acharb** [comment]
this has been added to dashboard-v2. See `LEDGER INFO` chart of https://metrics.stellar.org/?network=mainnet
