### ISSUE TITLE
Move to a new data viz library

### ISSUE THREAD

**Issue by dangdennis** [stellar/dashboard#96]
React-d3-components is hardly maintained anymore. To implement a feature addition for #91, I had to fork and update the implementation.

I'd recommend trying out:

1. [Nivo](https://nivo.rocks/bar), i.e. State of JS charts
2. [Victory](https://formidable.com/open-source/victory/gallery/), supported by Formidable
3. [React-viz](https://uber.github.io/react-vis/examples/showcases/plots), supported by Uber

**Comment by kostimarko** [comment]
I've started moving the data viz library to Nivo. I'm also taking a few other issues into consideration for new graphs and graph updates.
